### ISSUE TITLE
Stable unique id for threads

### ISSUE THREAD

**Issue by tekumara** [fizzbee-io/fizzbee#102]
The thread number can change during execution of an action.
For debugging it would be helpful if the thread id was stable and unique for a given execution path.

eg:
```
---
deadlock_detection: false
options:
    max_actions: 3
action_options:
    ReceiveSQS:
        max_concurrent_actions: 1
---


action Init:
    sqs_fifo = []
    db = []

atomic action Send:
    sqs_fifo.append(record(score=5, message='Hello'))

atomic  action ReceiveSQS:
    if sqs_fifo:
        process(sqs_fifo[0])
        oneof:
            sqs_fifo.pop(0)
            pass # Do nothing i.e, in this case, don't remove the message

fair action Increment:
    v = db
    v.append("i")
    db = v


func process(message):
    v = db
    v.append("p")
    db = v
```

In the explorer here, when ReceiveSQS starts it has `thread-1` but when `thread-0` completes, it becomes `thread-0` 

https://github.com/user-attachments/assets/5e291d69-81e8-491c-85b2-4a4225776215

**Comment by jp-fizzbee** [comment]
@tekumara Sorry about the delay. I just merged the fix and updated the playground. 

It was a bit of work as the model checker does deduplication if a same state can be reached from different order of operations and the deduplication logic has to be thread-order independent. Can you take a look at let me know if this works for you.

**Comment by tekumara** [comment]
Works well thank you (and I see it's now `action` rather than `thread`).
