### ISSUE TITLE
Where are the doc files located?

### ISSUE THREAD

**Issue by PoorlyDefinedBehaviour** [fizzbee-io/fizzbee#49]
Where are the files that contain the tutorials/blog posts that appear in the website? I didn't find them in this repo using text search so I'm assuming they are somewhere else.

**Comment by jp-fizzbee** [comment]
Yes, it is in a separate repo, at present it is private. It uses Hugo static site generator. I need to cleanup a bit before I make it public. I'm curious, are you planning to help with the documentation?

**Comment by jp-fizzbee** [comment]
If you want, I can add you to the documentation repo.

**Comment by PoorlyDefinedBehaviour** [comment]
> Yes, it is in a separate repo, at present it is private. It uses Hugo static site generator. I need to cleanup a bit before I make it public. I'm curious, are you planning to help with the documentation?

I was mostly going to fix a few typos that I encountered while reading the docs. But I'm willing to help with anything else :+1:

**Comment by jp-fizzbee** [comment]
I've sent you an invite to the repo to start with.

**Comment by PoorlyDefinedBehaviour** [comment]
I'm unable to create a PR since forks are disabled in the repo

**Comment by jayaprabhakar** [comment]
Gave write access. Can you try to now?

**Comment by PoorlyDefinedBehaviour** [comment]
Done. PR created.
