### ISSUE TITLE
Enable Explorer when assertions fail

### ISSUE THREAD

**Issue by tekumara** [fizzbee-io/fizzbee#88]
When using the playground I'd like to be able to use the Explorer even when assertions have failed. This would help debug the error.

PS: Really love this tool, the docs and examples - its been easy to get started with!

**Comment by jp-fizzbee** [comment]
Sure, I will work on that. 

I'm glad you liked fizzbee.

**Comment by jp-fizzbee** [comment]
Added this for the error path. 

For the actual explorer when things fail, I need to see how to reduce the ui clutter. For now, can you try disabling the assertions and get the explorer to work?
